import Payroll from "../models/payroll.js";
import createHttpError from "http-errors";
import Employee from "../models/employee.js";
import tryCatch from "../utils/tryCatchFn.js";
import { validatePayroll } from "../utils/validators.js";
import {
  createPayrollService,
  updatePayrollStatusService,
} from "../services/payroll.service.js";

export const createPayroll = tryCatch(async (req, res) => {
  const { error } = validatePayroll(req.body);
  if (error) throw new createHttpError(400, error.details[0].message);
  const employee = await Employee.findOne({ employeeId: req.body.employeeId });
  if (!employee) throw new createHttpError(404, "Employee not found");
  const payroll = await createPayrollService(employee, req);
  await payroll.save();
  res.status(201).json({
    msg: "Payroll created successfully",
    payroll,
  });
});

export const getPayrollById = tryCatch(async (req, res) => {
  const payroll = await Payroll.findOne({ payrollId: req.params.id });
  if (!payroll) throw new createHttpError(404, "Payroll not found");
  res.json({
    msg: "Payroll fetched successfully",
    payroll,
  });
});

export const getEmployeePayrolls = tryCatch(async (req, res) => {
  const { employeeId, year, month } = req.query;
  const query = { employeeId };

  if (year) query.year = parseInt(year);
  if (month) query.month = parseInt(month);

  const payrolls = await Payroll.find(query).sort({ year: -1, month: -1 });
  res.json({
    msg: "Payrolls fetched successfully",
    payrolls,
  });
});

export const updatePayrollStatus = tryCatch(async (req, res) => {
  const { status } = req.body;
  const payroll = await Payroll.findOne({ payrollId: req.params.id });
  if (!payroll) throw new createHttpError(404, "Payroll not found");
  const employee = await Employee.findOne({ employeeId: payroll.employeeId });
  if (!employee) throw new createHttpError(404, "Employee not found");
  const updatedStatus = await updatePayrollStatusService(
    status,
    payroll,
    employee
  );
  res.json({
    msg: "Payroll status updated successfully",
    updatedStatus,
  });
});

export const generatePayrolls = tryCatch(async (req, res) => {
  const employees = await Employee.find({ autoGenerateEnabled: true });
  const generated = [];

  for (const employee of employees) {
    if (Payroll.shouldGeneratePayroll(employee.lastAutoGenerated)) {
      const now = new Date();
      const payroll = new Payroll({
        employeeId: employee._id,
        month: now.getMonth() + 1,
        year: now.getFullYear(),
        salary: employee.salary,
        tax: employee.tax,
        payPeriod: {
          start: new Date(now.getFullYear(), now.getMonth(), 1),
          end: new Date(now.getFullYear(), now.getMonth() + 1, 0),
        },
      });

      await payroll.save();
      generated.push(payroll);
    }
  }
  res.json({
    msg: `Generated ${generated.length} payrolls`,
    payrolls: generated,
  });
});

export const getLatestPayroll = tryCatch(async (req, res, next) => {
  const page = parseInt(req.query.page) || 1;
  const limit = parseInt(req.query.limit) || 10;
  const skip = (page - 1) * limit;

  const latestPayroll = await Payroll.findOne().sort({ year: -1, month: -1 });
  let filter = {};
  if (latestPayroll) {
    // Step 2: Use the latest month and year to filter results
    filter = {
      month: latestPayroll.month,
      year: latestPayroll.year,
    };
  }

  const payrolls = await Payroll.find(filter)
    .populate("userId", "firstName lastName")
    .sort({ createdAt: -1 })
    .skip(skip)
    .limit(limit);

  if (!payrolls || payrolls.length === 0) {
    return next(createHttpError(404, "No payrolls found"));
  }
  const totalCount = await Payroll.countDocuments(filter);
  res.json({
    msg: "Payrolls fetched successfully",
    payrolls,
    pagination: {
      currentPage: page,
      totalPages: Math.ceil(totalCount / limit),
      totalPayrolls: totalCount,
      hasMore: skip + payrolls.length < totalCount,
    },
  });
});

export const deletePayroll = tryCatch(async (req, res, next) => {
  const { id: payrollId } = req.params;
  if (!payrollId) {
    return next(createHttpError(400, "Payroll id is required"));
  }
  const payroll = await Payroll.findByIdAndDelete(payrollId);
  if (!payroll) {
    return next(createHttpError(404, "Payroll not found"));
  }
  res.status(200).json({ msg: "Payroll deleted successfully" });
});
